# Generated by Django 5.1.5 on 2025-01-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_car_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
