# Generated by Django 5.1.5 on 2025-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_per_day',
            new_name='price_per_km',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
