# Generated by Django 5.1.5 on 2025-02-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
