# Generated by Django 5.1.5 on 2025-02-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_booking_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='image',
            new_name='license_image',
        ),
    ]
