# Generated by Django 5.1.5 on 2025-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_rename_image_booking_license_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_images/'),
        ),
    ]
