# Generated by Django 5.1.5 on 2025-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_booking_license_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='license_image',
        ),
        migrations.AddField(
            model_name='customer',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_images/'),
        ),
    ]
