# Generated by Django 5.1.5 on 2025-02-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_lat_long_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lat_long',
            name='user',
        ),
    ]
