# Generated by Django 5.1.5 on 2025-02-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_remove_lat_long_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='from_location_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='from_location_lon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='to_location_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='to_location_lon',
        ),
        migrations.AddField(
            model_name='booking',
            name='lat_long',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.lat_long'),
        ),
    ]
