# Generated by Django 5.1.5 on 2025-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_remove_booking_from_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lat_long',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
