# Generated by Django 5.1.5 on 2025-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_remove_booking_lat_long_customer_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
