# Generated by Django 5.1.5 on 2025-02-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
