# Generated by Django 5.1.5 on 2025-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
