# Generated by Django 5.1.5 on 2025-02-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_rename_created_at_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
